### ISSUE TITLE
Some release tags break the user-update feature

### ISSUE THREAD

**Issue by jim-thompson** [re3Dprinting/touchscreen#67]
I tagged a commit with "release/jt-test-2020.03.06". When I touched the "Check for Update" feature, I saw no updates, and saw the error "invalid literal for int() with base 10: 'jt-test-2020'" on stderr.

**Comment by plloppii** [comment]
So currently, the codebase is attemping to sort the tags based off the sematic version numbering of X.X.X. 
It was an attempt to show the latest releases on top of the list. Do we want to show versions that are outside the format of release/X.X.X?

Will put in more error catching so that the software doesn't crash.

**Comment by plloppii** [comment]
issue resolved in release release/beta/1.0.16
