### ISSUE TITLE
Deleted tags still appear as available releases.

### ISSUE THREAD

**Issue by jim-thompson** [re3Dprinting/touchscreen#69]
1. Create a release tag in Github
2. On touchscreen, do Check for Update. Verify that the release tag is there.
3. Delete the tag from Github.
4. On touchscreen, do Check for Update again. The deleted tag still appears as a valid update.

**Comment by plloppii** [comment]
Fixed in devel/1.0.20.

All tags with the prefix, devel/ release/ or hotfix/ are deleted. 
However, I feel that the correct solution would be to delete all the local tags and reupdate them with the ones existing on the remote repo. 

This can be done by:
git fetch --prune re3d "+refs/tags/*:refs/tags/*"

Any objections?

**Comment by plloppii** [comment]
fixed as of devel/1.0.24
